server:
  port: 8082

spring:
  application:
    name: rent-receipt

  # ===============================
  # PostgreSQL
  # ===============================
  datasource:
    url: jdbc:postgresql://172.31.249.236:5432/jsa_db
    username: jsa
    password: aya
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # ===============================
  # Redis
  # ===============================
  data:
    redis:
      host: 172.31.250.214
      port: 6379
      timeout: 2000

  # ===============================
  # Kafka
  # ===============================
  kafka:
    bootstrap-servers: 172.31.249.91:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: rent-receipt-group
      auto-offset-reset: earliest

# ===============================
# MinIO
# ===============================
minio:
  url: https://172.31.250.54:9000
  access-key: admin
  secret-key: admin123
  bucket: quittances

# ===============================
# Logging
# ===============================
logging:
  level:
    root: INFO
    com.jsahome: DEBUG
