server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://172.31.249.236:5432/jsa_db
    username: jsa
    password: aya
  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: false

  logging:
    level:
      org.hibernate.orm.connections.pooling: WARN
      org.hibernate.orm.connections: WARN
      org.hibernate: WARN

app:
  jwt:
    secret: "v9Qp2mL7xR4nK8tS1yC6hD3gF5jA0zW2"