http:
  routers:
    frontend-router:
      rule: "PathPrefix(`/`)"
      service: frontend
      priority: 1
      entryPoints:
        - web

    bff-router:
      rule: "PathPrefix(`/api`)"
      service: bff
      priority: 10
      middlewares:
        - strip-api
      entryPoints:
        - web

    chat-ws-router:
      rule: "PathPrefix(`/ws`)"
      service: bff
      priority: 10
      entryPoints:
        - web

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"

    add-cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
        accessControlAllowOriginList:
          - "http://172.31.252.169"
        accessControlMaxAge: 100
        addVaryHeader: true

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    bff:
      loadBalancer:
        servers:
          - url: "http://bff-service:8080"
